sudo: required
services:
  - docker
language: java
script: mvn clean install
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "springrestdemo"
  env: "Springrestdemo-env"
  bucket-name: "elasticbeanstalk-eu-central-1-243838082233"
  bucket-path: "springrestdemo"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
